repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.3.0
    hooks:
      - id: pycln
        args: [--config, pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        stages: [commit]